package com.suhba.database.enums;

public enum Country {
    ALGERIA, AUSTRALIA, BANGLADESH, CANADA, EGYPT, FRANCE, GERMANY, INDONESIA, IRAN, IRAQ, JAPAN, JORDAN, KUWAIT, LEBANON, MALAYSIA, MOROCCO, OMAN, PAKISTAN, QATAR, SAUDI_ARABIA, SOUTH_KOREA, SUDAN, SWEDEN, SWITZERLAND, TUNISIA, TURKEY,UNITED_ARAB_EMIRATES, UNITED_KINGDOM, UNITED_STATES, YEMEN
}
